# Generated by Django 3.2 on 2022-05-04 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_adult_content',
            field=models.BooleanField(default=False),
        ),
    ]
