# Generated by Django 3.2 on 2022-05-03 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sso', '0003_auto_20220503_0601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
    ]
